In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [14]:
arr1=np.array([1,2,3])

In [15]:
type(arr1)

numpy.ndarray

In [16]:
arr1

array([1, 2, 3])

In [17]:
# heart_disease_prediction: (75-80%)
# diabetes_prediction: (74-79%)

In [18]:
df_heart=pd.read_csv("ml_datasets/Heart_disease_cleveland_new.csv")

df_heart

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,0,145,233,1,2,150,0,2.3,2,0,2,0
1,67,1,3,160,286,0,2,108,1,1.5,1,3,1,1
2,67,1,3,120,229,0,2,129,1,2.6,1,2,3,1
3,37,1,2,130,250,0,0,187,0,3.5,2,0,1,0
4,41,0,1,130,204,0,2,172,0,1.4,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,0,110,264,0,0,132,0,1.2,1,0,3,1
299,68,1,3,144,193,1,0,141,0,3.4,1,2,3,1
300,57,1,3,130,131,0,0,115,1,1.2,1,1,3,1
301,57,0,1,130,236,0,2,174,0,0.0,1,1,1,1
302,38,1,2,138,175,0,0,173,0,0.0,0,0,1,0

In [19]:
from sklearn.tree import DecisionTreeClassifier
import numpy as np

# Sample dataset
X_train = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y_train = np.array([0, 1, 1, 0])

# Train Decision Tree
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

# New data point
X_test = np.array([[2, 3]])

# Get probabilities
probs = clf.predict_proba(X_test)
print(probs)  # Output: [[prob_class_0, prob_class_1]]

[[1. 0.]]